### ISSUE TITLE
Сторонние модули

### ISSUE THREAD

**Issue by dipiash** [fullalive/test-zayc#1]
1. Можно ли было для этой задачи обойтись без использования сторонних модулей?
2. Что дают модули ```install``` и ```npm``` перечисленные в package.json?
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/package.json#L12
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/package.json#L14

**Comment by fullalive** [comment]
1) Можно было обойтись без сторонних модулей
2) install и npm были сгенерированы командой `npm init`

**Comment by dipiash** [comment]
> install и npm были сгенерированы командой npm init

Точно?
Это выход npm init (v6.4.1) и сколько я помню никогда небыло значений по умолчанию в секции `dependencies` и в предыдущих версиях
```json
{
  "name": "qwe",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
___________________

Какую функцию они выполняют в данной программе?

**Comment by fullalive** [comment]
В данной программе эти модули не несут никакой смысловой нагрузки.
По поводу моего предыдущего ответа, ошибся. Сам эти модули не устанавливал сюда,  когда их увидел сам удивился откуда они взялись, поэтому подумал на `npm init`, что было не обоснованно.
Этими модулями пользоваться не приходилось ранее, поставил модуль `npm`, поигрался, с его помощью можно, например, программно выполнять команды `npm`.

**Comment by dipiash** [comment]
Окей)
Можете почистить код от всего лишнего и оставить только то, что относится к задаче?

**Comment by fullalive** [comment]
Сделал
