### ISSUE TITLE
Код в util/md5

### ISSUE THREAD

**Issue by dipiash** [fullalive/test-zayc#2]
1. Почему был оставлен этот код? и не использован в app.js?
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/uitls/md5.js#L1

2. Почему был выбран js-md5?
3. Есть ли более оптимальный способ (по ресурсам)?

**Comment by fullalive** [comment]
1) Код был оставлен для того, чтобы можно было не ставить npm пакеты, раскомментировав строчку в app.js все бы заработало
2) js-md5 был выбран исходя из того, что он самый популярный, так же он за собой тянет не сильно много зависимостей относительно большинства других.
3) Оптимальней думаю способ со своим файлом md5, который есть в проекте. Так как ни одного лишнего пакета в проекте не будет

**Comment by dipiash** [comment]
> Оптимальней думаю способ со своим файлом md5, который есть в проекте. Так как ни одного лишнего пакета в проекте не будет

Имелось в виду - способы не использующие md5 хэш. Как еще можно в JS (есть несколько вариантов) сравнить массивы?

**Comment by fullalive** [comment]
Можно посимвольно проверять и сравнивать, можно, например, преобразовать массив в строку и сравнивать их.
