### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by dipiash** [fullalive/test-zayc#3]
1. Как вы заливали код в репозиторий?
2. Нужно ли хранить в репозитории .gitignore файл?

**Comment by fullalive** [comment]
1) Код заливал посредством WebStorm
2) .gitignore нужен обязательно

**Comment by dipiash** [comment]
> .gitignore нужен обязательно

Ага) А какие проблемы (или может их нет) мы решим этим?

**Comment by fullalive** [comment]
При коммите git не будет предлагать файлы, добавленные в .`gitignore`. Благодаря этому можно избежать случайного коммита файлов, которые не должны быть закоммичены

**Comment by dipiash** [comment]
Принимается!
