### ISSUE TITLE
Структура данных для хранения шагов

### ISSUE THREAD

**Issue by dipiash** [fullalive/test-zayc#4]
Почему для хранения истории было выбрано дерево? Есть ли альтернативы (будут ли они оптимальнее по ресурсам)?
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/app.js#L4

**Comment by fullalive** [comment]
Альтернатив для хранения много, но для такого большого количества данных, которые надо перебирать на каждой итерации, мне показалось, дерево поиска подходит лучше всего.

**Comment by dipiash** [comment]
Хорошо, если сравнить [сложноть](https://ru.wikipedia.org/wiki/%D0%94%D0%B2%D0%BE%D0%B8%D1%87%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0), какое будет (если оно есть) более оптимальное решение?
А какие критерии важны для данной задачи (если сравнивать алгоритмы для поиска)?

**Comment by fullalive** [comment]
Для этой задачи важна скорость поиска в большом количестве данных, сравнительно, например, с линейным поиском, с таким объемом данных дерево справляется во много раз быстрее. Поэтому оптимальным я посчитал именно это решение

**Comment by dipiash** [comment]
А если бы мы хранили шаги в объекте (ключ: значение, без вложенности) или массиве?

**Comment by fullalive** [comment]
На первой итерации написания решения использовал именно массив, и результат был печальным, что не удивительно. Программа выполнялась бы не менее суток.
Потом начал думать в сторону деревьев. В объекте хранить получается тоже быстро, но все-таки сравнительно с деревьями, объект хоть и немного, но проигрывает в скорости.

**Comment by dipiash** [comment]
С массивами: имеете в виду решения с различной длиной или конкретно для этого случая?

Если брать обьект, разве не получается, что мы доступаемся до свойства за один шаг, а в случае с деревом за несколько?

**Comment by fullalive** [comment]
С массивами конкретно для этого случая. А с объектами, я проверял скорость, и этот вариант оказался чуть менее эффективен, чем вариант с деревьями.

**Comment by dipiash** [comment]
Хорошо, чтобы добить вопрос до конца так же пойдем от сложности:
1) верно ли говорить о сложности и будет ли она одинаковой в различных браузерах?
2) что влияет на разность в скорости при обычном обьекте и дереве (возьмем только Chrome)? Если сравнить при большем количестве шагов (на 1, 2, 3 и т.д. порядка) , чем в примере задачи, что даст более производительный результат и как сильно он будет отличаться?
