### ISSUE TITLE
Поиск максимума

### ISSUE THREAD

**Issue by dipiash** [fullalive/test-zayc#5]
Есть ли стандарные средства языка для поиска максимума? (Если есть, то какое решение работает оптимальнее)?
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/app.js#L51

**Comment by fullalive** [comment]
Есть стандартное средство, которое позволяет найти максимально из набора чисел. Запись выглядела бы так: `const max = Math.max(...array)`. Но в таком случае в переменной max будет только максимальное число, а для решения мне требовался также его индекс. Поэтому было принято такое решение.

**Comment by dipiash** [comment]
А если сравнить по производительности?
Какое будет решение оптимальнее использовать `Math.max(...array)` и поиск индекса дополнительно или перебор, как в текущем варианте?

**Comment by fullalive** [comment]
Вариант с `Math.max(...array)` производительнее, и при этом компактней, сделал выбор в пользу другого решения , упустив одну очень важную деталь в принципе работы методов `findIndex` и `indexOf`, которую осознал только сейчас

**Comment by dipiash** [comment]
А как сравнивали?
Сталкивались с инструментами сравнения производительности, например, [1](http://jsben.ch/n5ED1), [2](http://jsben.ch/MEGVI)?

**Comment by fullalive** [comment]
С выше описанным инструментом сравнения сталкивался. Конкретно в этом случае использовал не его, так как были проблемы с интернетом в тот момент, проверил, вставив код в консоль браузера и использовав `performance.now()`.

**Comment by dipiash** [comment]
Принимается!
