### ISSUE TITLE
Использование переменных

### ISSUE THREAD

**Issue by dipiash** [fullalive/test-zayc#6]
Можно ли считать первый хэш внутри массива? Будет ли это правильнее/понятнее с точки зрения написания кода и выполнения одних и техже операций, но в одном мместе?
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/app.js#L98

Можно ли первую инициализацию заведомо поставить false? 
https://github.com/fullalive/test-zayc/blob/85b6aeafb8ca491924627f4813a82f358c947c62/app.js#L99

**Comment by fullalive** [comment]
1) Если имелось ввиду считать хэш внутри цикла, то да, даже нужно было
2) Первая инициализация `isInHistory` может и должна быть false
